name: Warm

on:
  schedule:
    #       ┌──────────────── minute (0 - 59)
    #       │ ┌────────────── hour (0 - 23)
    #       │ │ ┌──────────── day of the month (1 - 31)
    #       │ │ │   ┌──────── month (1 - 12 or JAN-DEC)
    #       │ │ │   │ ┌────── day of the week (0 - 6 or SUN-SAT)
    #       │ │ │   │ │
    #       │ │ │   │ │
    #       │ │ │   │ │
    #       * * *   * *
    - cron: 0 0 */2 * *

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  warm:
    runs-on: ubuntu-latest

    steps:
      - name: cURL Swagger
        run: curl https://$GITHUB_REPOSITORY_OWNER-$REPOSITORY_NAME.hf.spaces